#version: "3.2"
version: "3.5"

services:
  masscan:
    command: $CIDR_BLOCK -p$PORTS -oJ masscan.json --rate $RATE
    build:
      context: masscan/
    volumes:
      - type: bind
        source: ./results
        target: /home/scan
        read_only: false
    hostname: "{{.Node.Hostname}}-masscan"
    #networks:
    #  - elk
    #
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VER}
    user: root
    volumes:
      - type: bind
        source: ./results
        target: /data
        read_only: true
      - type: bind
        source: ./filebeat
        target: /usr/share/filebeat/data
      #- ${PWD}/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      - ELK_HOST=${ELK_HOST}
      - ELK_USERNAME=${ELK_USERNAME:-elastic}
      - ELK_PASSWORD=${ELK_PASSWORD:-changeme}
    hostname: "{{.Node.Hostname}}-filebeat"

#file: $PWD/filebeat/config/filebeat.yml
